version: 0.2

phases:
  build:
    commands:
      - echo build started on $(date)
      - aws ecs get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  post_build:
    commands:
      - echo build completed on $(date)
      - echo Pushing the Docker image ...
