version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.15.2

workflows:
  build-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          fileters:
            branches:
              only:
                - dev
                - main
